---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sds-replicated-volume-scheduler-extender
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-scheduler-extender")) | nindent 2 }}
data:
  scheduler-extender-config.yaml: |-
    listen: ":8099"
    health-probe-bind-address: ":8081"
    default-divisor: 1
{{- if eq .Values.sdsReplicatedVolume.logLevel "ERROR" }}
    log-level: "0"
{{- else if eq .Values.sdsReplicatedVolume.logLevel "WARN" }}
    log-level: "1"
{{- else if eq .Values.sdsReplicatedVolume.logLevel "INFO" }}
    log-level: "2"
{{- else if eq .Values.sdsReplicatedVolume.logLevel "DEBUG" }}
    log-level: "3"
{{- else if eq .Values.sdsReplicatedVolume.logLevel "TRACE" }}
    log-level: "4"
    {{- end }}

{{- if and (not (eq "dev" .Values.global.deckhouseVersion)) (semverCompare "<1.64" .Values.global.deckhouseVersion) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linstor-scheduler
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-scheduler")) | nindent 2 }}
data:
  scheduler-config.yaml: |-
    {{- if semverCompare ">= 1.26" .Values.global.discovery.kubernetesVersion }}
    apiVersion: kubescheduler.config.k8s.io/v1
    {{- else }}
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    {{- end }}
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: linstor
    extenders:
      - urlPrefix: http://localhost:8099
        filterVerb: filter
        prioritizeVerb: prioritize
        weight: 5
        enableHTTPS: false
        httpTimeout: 300s
        nodeCacheCapable: false
{{- end }}