---
apiVersion: v1
kind: Secret
metadata:
  name: linstor-scheduler-extender-https-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-scheduler-extender")) | nindent 2 }}
    
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.sdsReplicatedVolume.internal.customSchedulerExtenderCert.ca }}
  tls.crt: {{ .Values.sdsReplicatedVolume.internal.customSchedulerExtenderCert.crt }}
  tls.key: {{ .Values.sdsReplicatedVolume.internal.customSchedulerExtenderCert.key }}