{{- if or (hasPrefix "dev" .Values.global.deckhouseVersion) (hasSuffix "dev" .Values.global.deckhouseVersion) (semverCompare ">=1.64" .Values.global.deckhouseVersion) }}
---
apiVersion: v1
kind: Service
metadata:
  name: linstor-scheduler-extender
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-scheduler-extender" )) | nindent 2 }}
spec:
  type: ClusterIP
  ports:
    - port: 8099
      targetPort: 8099
      protocol: TCP
      name: http
  selector:
    app: linstor-scheduler-extender
{{- end }}