apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:sds-replicated-volume
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
rules:
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["replicatedvolumereplicas"]
    verbs:  ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["replicatedvolumereplicas/status"]
    verbs:  ["patch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:sds-replicated-volume
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:sds-replicated-volume
  apiGroup: rbac.authorization.k8s.io
