{{- if not .Values.sdsReplicatedVolume.useLinstor }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "agent")) | nindent 2 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:agent
  {{- include "helm_lib_module_labels" (list . (dict "app" "agent")) | nindent 2 }}
rules:
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["replicatedvolumereplicas"]
    verbs:  ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["replicatedvolumereplicas/status"]
    verbs:  ["patch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:agent
  {{- include "helm_lib_module_labels" (list . (dict "app" "agent")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:agent-rbac-proxy
  {{- include "helm_lib_module_labels" (list . (dict "app" "agent")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: d8-{{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:rbac-proxy
{{- end }}
