{{- if .Values.sdsReplicatedVolume.internal.newControlPlane }}
{{- if not (contains "all_completed" (default "" .Values.sdsReplicatedVolume.internal.controlPlaneMigration)) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: control-plane-migrator
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "control-plane-migrator")) | nindent 2 }}
spec:
  backoffLimit: 2
  template:
    metadata:
      {{- include "helm_lib_module_labels" (list . (dict "app" "control-plane-migrator")) | nindent 6 }}
    spec:
      serviceAccountName: control-plane-migrator
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ .Chart.Name }}-module-registry
      containers:
      - name: migrator
        image: {{ include "helm_lib_module_image" (list . "linstorMigrator") }}
        imagePullPolicy: IfNotPresent
        args:
          - --log-level
          - debug
{{- end }}
{{- end }}
