---
apiVersion: v1
kind: Secret
metadata:
  name: drbd-build-server-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "drbd-build-server")) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- with .Values.sdsReplicatedVolume.internal.drbdBuildServerCert }}
  tls.crt: {{ .crt | b64enc }}
  tls.key: {{ .key | b64enc }}
  ca.crt: {{ .ca | b64enc }}
  {{- end }}
