version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - fmt:.*,[rR]ead|[wW]rite|[cC]lose
        - io:Copy
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: ST1005.*
      - path: (.+)\.go$
        text: should not use dot imports
      - path: (.+)\.go$
        text: don't use an underscore in package name
      - path: (.+)\.go$
        text: 'exported: .*'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/deckhouse)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
