run:
  timeout: 10m

issues:
  exclude:
    - ST1005.*
    - "should not use dot imports"
    - "don't use an underscore in package name"
    - "exported: .*"

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/deckhouse)

  errcheck:
    ignore: fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - gci
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - copyloopvar
