---
apiVersion: v1
kind: Secret
metadata:
  name: webhooks-ca
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- with .Values.sdsReplicatedVolume.internal.webhooksCA }}
  tls.crt: {{ .crt }}
  tls.key: {{ .key }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: webhooks-https-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhooks")) | nindent 2 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.ca | b64enc }}
  tls.crt: {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.crt | b64enc }}
  tls.key: {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.key | b64enc }}
