---
apiVersion: v1
kind: Secret
metadata:
  name: webhooks-https-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict
    "app" "webhooks"
    "storage.deckhouse.io/internal-cert-name" "customWebhookCert"
  )) | nindent 2 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.ca }}
  tls.crt: {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.crt }}
  tls.key: {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.key }}
