---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "d8-sds-replicated-volume-rsp-validation"
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
webhooks:
  - name: "d8-sds-replicated-volume-rsp-validation.storage.deckhouse.io"
    rules:
      - apiGroups: ["storage.deckhouse.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["replicatedstoragepools"]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: "d8-{{ .Chart.Name }}"
        name: "webhooks"
        path: "/rsp-validate"
      caBundle: |
        {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.ca | b64enc }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "d8-sds-replicated-volume-rsc-validation"
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
webhooks:
  - name: "d8-sds-replicated-volume-rsc-validation.storage.deckhouse.io"
    rules:
      - apiGroups: ["storage.deckhouse.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["replicatedstorageclasses"]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: "d8-{{ .Chart.Name }}"
        name: "webhooks"
        path: "/rsc-validate"
      caBundle: |
        {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.ca | b64enc }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "d8-sds-replicated-volume-sc-validation"
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
webhooks:
  - name: "d8-sds-replicated-volume-sc-validation.storage.deckhouse.io"
    rules:
      - apiGroups: ["storage.k8s.io"]
        apiVersions: ["v1"]
        operations: ["*"]
        resources: ["storageclasses"]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: "d8-{{ .Chart.Name }}"
        name: "webhooks"
        path: "/sc-validate"
      caBundle: |
        {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.ca | b64enc }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "d8-sds-replicated-volume-pvc-validation"
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
webhooks:
  - name: "d8-sds-replicated-volume-pvc-validation.storage.deckhouse.io"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["persistentvolumeclaims"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "d8-{{ .Chart.Name }}"
        name: "webhooks"
        path: "/pvc-validate"
      caBundle: |
        {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.ca | b64enc }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
