---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "d8-sds-replicated-volume-dsc-validation"
webhooks:
  - name: "d8-sds-replicated-volume-dsc-validation.storage.deckhouse.io"
    rules:
      - apiGroups: ["storage.deckhouse.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["replicatedstorageclasses"]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: "d8-{{ .Chart.Name }}"
        name: "webhooks"
        path: "/rsc-validate"
      caBundle: |
        {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.ca }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "d8-sds-replicated-volume-sc-validation"
webhooks:
  - name: "d8-sds-replicated-volume-sc-validation.storage.deckhouse.io"
    rules:
      - apiGroups: ["storage.k8s.io"]
        apiVersions: ["v1"]
        operations: ["*"]
        resources: ["storageclasses"]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: "d8-{{ .Chart.Name }}"
        name: "webhooks"
        path: "/sc-validate"
      caBundle: |
        {{ .Values.sdsReplicatedVolume.internal.customWebhookCert.ca }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
