{{- if or (hasPrefix "dev" .Values.global.deckhouseVersion) (hasSuffix "dev" .Values.global.deckhouseVersion) (semverCompare ">=1.64" .Values.global.deckhouseVersion) }}
apiVersion: deckhouse.io/v1alpha1
kind: KubeSchedulerWebhookConfiguration
metadata:
  name: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . ) | nindent 2 }}
webhooks:
- weight: 5
  failurePolicy: Ignore
  clientConfig:
    service:
      name: linstor-scheduler-extender
      namespace: d8-{{ .Chart.Name }}
      port: 8099
      path: /
    caBundle: {{ .Values.sdsReplicatedVolume.internal.customSchedulerExtenderCert.ca | b64enc }}
  timeoutSeconds: 5

{{- end }}