type: object
properties:
  # TODO: Set the option below to deprecated when the PR https://github.com/deckhouse/deckhouse/pull/7263 will reach RockSolid channel
  registryScheme:
    type: string
    description: Change this parameter to "http" if the module registry does not support TLS.
    default: https
  logLevel:
    type: string
    enum:
      - ERROR
      - WARN
      - INFO
      - DEBUG
      - TRACE
    description: Module log level
    default: INFO
  drbdPortRange:
    type: object
    description: Settings for DRBD TCP ports
    default: {}
    properties:
      minPort:
        type: integer
        default: 7000
        description: |
          DRBD ports range start
      maxPort:
        type: integer
        default: 7999
        description: |
          DRBD ports range end
  enableThinProvisioning:
    type: boolean
    default: false
    description: Allow thin LVM volumes usage
  dataNodes:
    type: object
    description: Settings for Linstor on nodes with data
    default: {}
    properties:
      nodeSelector:
        type: object
        default:
          kubernetes.io/os: linux
        additionalProperties:
          type: string
        description: |
          The same as in the Pods `spec.nodeSelector` parameter in Kubernetes.

          If parameter is omitted, Linstor nodes will be placed on all nodes.

          **Caution!** Changing this parameter does not result in data redistribution. If node with data no longer matches the `nodeSelector`, data on that node will become inaccessible.
  backup:
    type: object
    description: Module backup settings
    properties:
      enabled:
        type: boolean
        default: true
        description: Module backup state
      retentionCount:
        type: integer
        default: 3
        description: Number of backups to keep
      schedule:
        type: string
        default: "0 3 * * *"
        description: Backup schedule