type: object
properties:
  logLevel:
    type: string
    enum:
      - ERROR
      - WARN
      - INFO
      - DEBUG
      - TRACE
    description: Module log level
    default: INFO
  dataNodes:
    type: object
    description: Settings for Linstor on nodes with data
    default: {}
    properties:
      nodeSelector:
        type: object
        default:
          kubernetes.io/os: linux
        additionalProperties:
          type: string
        description: |
          The same as in the Pods `spec.nodeSelector` parameter in Kubernetes.

          If parameter is omitted, Linstor nodes will be placed on all nodes.

          **Caution!** Changing this parameter does not result in data redistribution. If node with data no longer matches the `nodeSelector`, data on that node will become inaccessible.
  backup:
    type: object
    description: Module backup settings
    properties:
      enabled:
        type: boolean
        default: true
        description: Module backup state
      retentionCount:
        type: integer
        default: 3
        description: Number of backups to keep
      schedule:
        type: string
        default: "0 3 * * *"
        description: Backup schedule