x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    x-required-for-helm:
    - httpsClientCert
    - httpsControllerCert
    - sslControllerCert
    - sslNodeCert
    - drbdVersion
    - nodesHash
    properties:
      drbdVersion:
        type: string
        default: "9.2.5"
      nodesHash:
        type: string
        default: "8411fa3e4d61e760f3ad8251aa2b1421fcba04b9362763920c98268e0ef06a7d"
      masterPassphrase:
        type: string
      httpsClientCert:
        type: object
        default: {}
        x-required-for-helm:
        - crt
        - key
        - ca
        properties:
          crt:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          key:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          ca:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
      httpsControllerCert:
        type: object
        default: {}
        x-required-for-helm:
        - crt
        - key
        - ca
        properties:
          crt:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          key:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          ca:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
      sslControllerCert:
        type: object
        default: {}
        x-required-for-helm:
        - crt
        - key
        - ca
        properties:
          crt:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          key:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          ca:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
      sslNodeCert:
        type: object
        default: {}
        x-required-for-helm:
        - crt
        - key
        - ca
        properties:
          crt:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          key:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          ca:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
      spaasCert:
        type: object
        default: {}
        x-required-for-helm:
        - crt
        - key
        - ca
        properties:
          crt:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          key:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          ca:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
      webhookCert:
        type: object
        default: {}
        x-required-for-helm:
        - crt
        - key
        - ca
        properties:
          crt:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          key:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          ca:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
      customWebhookCert:
        type: object
        default: {}
        x-required-for-helm:
        - crt
        - key
        - ca
        properties:
          crt:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          key:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
          ca:
            type: string
            x-examples: ["YjY0ZW5jX3N0cmluZwo="]
