{{- if .Values.sdsReplicatedVolume.newControlPlane }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:{{ .Chart.Name }}:controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - nodes
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - replicatedstorageclasses
      - replicatedstoragepools
      - replicatedvolumes
      - replicatedvolumeattachments
      - replicatedvolumereplicas
      - drbdresources
      - drbdresourceoperations
      - drbdnodeoperations
      - lvmvolumegroups
      - lvmlogicalvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - replicatedstorageclasses/status
      - replicatedstoragepools/status
      - replicatedvolumes/status
      - replicatedvolumeattachments/status
      - replicatedvolumereplicas/status
      - drbdresources/status
      - drbdresourceoperations/status
      - drbdnodeoperations/status
      - lvmvolumegroups/status
      - lvmlogicalvolumes/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - replicatedstorageclasses/finalizers
      - replicatedstoragepools/finalizers
      - replicatedvolumes/finalizers
      - replicatedvolumeattachments/finalizers
      - replicatedvolumereplicas/finalizers
      - drbdresources/finalizers
      - drbdresourceoperations/finalizers
      - drbdnodeoperations/finalizers
      - lvmvolumegroups/finalizers
      - lvmlogicalvolumes/finalizers
    verbs:
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:controller
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
rules:
  # --- Pods: read-only (agent readiness checks) ---
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  # --- Leader election: specific Lease ---
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["sds-replicated-volume-controller"]
    verbs: ["get", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]

  # --- Events: leader election event recording ---
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: Role
  name: controller
  apiGroup: rbac.authorization.k8s.io
{{- end }}
