{{- if not .Values.sdsReplicatedVolume.useLinstor }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "controller")) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:{{ .Chart.Name }}:controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "controller")) | nindent 2 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["lvmlogicalvolumes", "replicatedvolumereplicas"]
    verbs: ["list", "get", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["replicatedvolumes", "replicatedvolumes/status"]
    verbs: ["list", "get", "watch", "patch", "update"]
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["lvmvolumegroups", "lvmvolumegroups/status", "lvmlogicalvolumes/status", "replicatedvolumereplicas/status"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:controller
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "controller")) | nindent 2 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "controller")) | nindent 2 }}
subjects:
- kind: ServiceAccount
  name: controller
  namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: Role
  name: controller
  apiGroup: rbac.authorization.k8s.io
{{- end }}
