//go:build !ignore_autogenerated

/*
Copyright  Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Address) DeepCopyInto(out *Address) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Address.
func (in *Address) DeepCopy() *Address {
	if in == nil {
		return nil
	}
	out := new(Address)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStatus) DeepCopyInto(out *ConnectionStatus) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]PathStatus, len(*in))
		copy(*out, *in)
	}
	if in.PeerDevices != nil {
		in, out := &in.PeerDevices, &out.PeerDevices
		*out = make([]PeerDeviceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatus.
func (in *ConnectionStatus) DeepCopy() *ConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBD) DeepCopyInto(out *DRBD) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(DRBDConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Actual != nil {
		in, out := &in.Actual, &out.Actual
		*out = new(DRBDActual)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(DRBDStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = new(DRBDErrors)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBD.
func (in *DRBD) DeepCopy() *DRBD {
	if in == nil {
		return nil
	}
	out := new(DRBD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBDActual) DeepCopyInto(out *DRBDActual) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBDActual.
func (in *DRBDActual) DeepCopy() *DRBDActual {
	if in == nil {
		return nil
	}
	out := new(DRBDActual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBDCmdError) DeepCopyInto(out *DRBDCmdError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBDCmdError.
func (in *DRBDCmdError) DeepCopy() *DRBDCmdError {
	if in == nil {
		return nil
	}
	out := new(DRBDCmdError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBDConfig) DeepCopyInto(out *DRBDConfig) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(Address)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make(map[string]Peer, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBDConfig.
func (in *DRBDConfig) DeepCopy() *DRBDConfig {
	if in == nil {
		return nil
	}
	out := new(DRBDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBDErrors) DeepCopyInto(out *DRBDErrors) {
	*out = *in
	if in.FileSystemOperationError != nil {
		in, out := &in.FileSystemOperationError, &out.FileSystemOperationError
		*out = new(DRBDMessageError)
		**out = **in
	}
	if in.ConfigurationCommandError != nil {
		in, out := &in.ConfigurationCommandError, &out.ConfigurationCommandError
		*out = new(DRBDCmdError)
		**out = **in
	}
	if in.SharedSecretAlgSelectionError != nil {
		in, out := &in.SharedSecretAlgSelectionError, &out.SharedSecretAlgSelectionError
		*out = new(SharedSecretUnsupportedAlgError)
		**out = **in
	}
	if in.LastPrimaryError != nil {
		in, out := &in.LastPrimaryError, &out.LastPrimaryError
		*out = new(DRBDCmdError)
		**out = **in
	}
	if in.LastSecondaryError != nil {
		in, out := &in.LastSecondaryError, &out.LastSecondaryError
		*out = new(DRBDCmdError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBDErrors.
func (in *DRBDErrors) DeepCopy() *DRBDErrors {
	if in == nil {
		return nil
	}
	out := new(DRBDErrors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBDMessageError) DeepCopyInto(out *DRBDMessageError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBDMessageError.
func (in *DRBDMessageError) DeepCopy() *DRBDMessageError {
	if in == nil {
		return nil
	}
	out := new(DRBDMessageError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBDResource) DeepCopyInto(out *DRBDResource) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(DRBDResourceConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBDResource.
func (in *DRBDResource) DeepCopy() *DRBDResource {
	if in == nil {
		return nil
	}
	out := new(DRBDResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBDResourceConfig) DeepCopyInto(out *DRBDResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBDResourceConfig.
func (in *DRBDResourceConfig) DeepCopy() *DRBDResourceConfig {
	if in == nil {
		return nil
	}
	out := new(DRBDResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBDStatus) DeepCopyInto(out *DRBDStatus) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]DeviceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]ConnectionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBDStatus.
func (in *DRBDStatus) DeepCopy() *DRBDStatus {
	if in == nil {
		return nil
	}
	out := new(DRBDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostStatus) DeepCopyInto(out *HostStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostStatus.
func (in *HostStatus) DeepCopy() *HostStatus {
	if in == nil {
		return nil
	}
	out := new(HostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathStatus) DeepCopyInto(out *PathStatus) {
	*out = *in
	out.ThisHost = in.ThisHost
	out.RemoteHost = in.RemoteHost
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathStatus.
func (in *PathStatus) DeepCopy() *PathStatus {
	if in == nil {
		return nil
	}
	out := new(PathStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Peer) DeepCopyInto(out *Peer) {
	*out = *in
	out.Address = in.Address
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Peer.
func (in *Peer) DeepCopy() *Peer {
	if in == nil {
		return nil
	}
	out := new(Peer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerDeviceStatus) DeepCopyInto(out *PeerDeviceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerDeviceStatus.
func (in *PeerDeviceStatus) DeepCopy() *PeerDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(PeerDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClass) DeepCopyInto(out *ReplicatedStorageClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClass.
func (in *ReplicatedStorageClass) DeepCopy() *ReplicatedStorageClass {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedStorageClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassConfiguration) DeepCopyInto(out *ReplicatedStorageClassConfiguration) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SystemNetworkNames != nil {
		in, out := &in.SystemNetworkNames, &out.SystemNetworkNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.EligibleNodesPolicy = in.EligibleNodesPolicy
	if in.NodeLabelSelector != nil {
		in, out := &in.NodeLabelSelector, &out.NodeLabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassConfiguration.
func (in *ReplicatedStorageClassConfiguration) DeepCopy() *ReplicatedStorageClassConfiguration {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassEligibleNode) DeepCopyInto(out *ReplicatedStorageClassEligibleNode) {
	*out = *in
	if in.LVMVolumeGroups != nil {
		in, out := &in.LVMVolumeGroups, &out.LVMVolumeGroups
		*out = make([]ReplicatedStorageClassEligibleNodeLVMVolumeGroup, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassEligibleNode.
func (in *ReplicatedStorageClassEligibleNode) DeepCopy() *ReplicatedStorageClassEligibleNode {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassEligibleNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassEligibleNodeLVMVolumeGroup) DeepCopyInto(out *ReplicatedStorageClassEligibleNodeLVMVolumeGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassEligibleNodeLVMVolumeGroup.
func (in *ReplicatedStorageClassEligibleNodeLVMVolumeGroup) DeepCopy() *ReplicatedStorageClassEligibleNodeLVMVolumeGroup {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassEligibleNodeLVMVolumeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassEligibleNodesDriftPolicy) DeepCopyInto(out *ReplicatedStorageClassEligibleNodesDriftPolicy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(ReplicatedStorageClassEligibleNodesDriftRollingUpdate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassEligibleNodesDriftPolicy.
func (in *ReplicatedStorageClassEligibleNodesDriftPolicy) DeepCopy() *ReplicatedStorageClassEligibleNodesDriftPolicy {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassEligibleNodesDriftPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassEligibleNodesDriftRollingUpdate) DeepCopyInto(out *ReplicatedStorageClassEligibleNodesDriftRollingUpdate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassEligibleNodesDriftRollingUpdate.
func (in *ReplicatedStorageClassEligibleNodesDriftRollingUpdate) DeepCopy() *ReplicatedStorageClassEligibleNodesDriftRollingUpdate {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassEligibleNodesDriftRollingUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassEligibleNodesPolicy) DeepCopyInto(out *ReplicatedStorageClassEligibleNodesPolicy) {
	*out = *in
	out.NotReadyGracePeriod = in.NotReadyGracePeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassEligibleNodesPolicy.
func (in *ReplicatedStorageClassEligibleNodesPolicy) DeepCopy() *ReplicatedStorageClassEligibleNodesPolicy {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassEligibleNodesPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassEligibleNodesWorldState) DeepCopyInto(out *ReplicatedStorageClassEligibleNodesWorldState) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassEligibleNodesWorldState.
func (in *ReplicatedStorageClassEligibleNodesWorldState) DeepCopy() *ReplicatedStorageClassEligibleNodesWorldState {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassEligibleNodesWorldState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassList) DeepCopyInto(out *ReplicatedStorageClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReplicatedStorageClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassList.
func (in *ReplicatedStorageClassList) DeepCopy() *ReplicatedStorageClassList {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedStorageClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassRollingUpdateInProgress) DeepCopyInto(out *ReplicatedStorageClassRollingUpdateInProgress) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassRollingUpdateInProgress.
func (in *ReplicatedStorageClassRollingUpdateInProgress) DeepCopy() *ReplicatedStorageClassRollingUpdateInProgress {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassRollingUpdateInProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassRollingUpdateStrategy) DeepCopyInto(out *ReplicatedStorageClassRollingUpdateStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassRollingUpdateStrategy.
func (in *ReplicatedStorageClassRollingUpdateStrategy) DeepCopy() *ReplicatedStorageClassRollingUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassRollingUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassRolloutStrategy) DeepCopyInto(out *ReplicatedStorageClassRolloutStrategy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(ReplicatedStorageClassRollingUpdateStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassRolloutStrategy.
func (in *ReplicatedStorageClassRolloutStrategy) DeepCopy() *ReplicatedStorageClassRolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassRolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassSpec) DeepCopyInto(out *ReplicatedStorageClassSpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeLabelSelector != nil {
		in, out := &in.NodeLabelSelector, &out.NodeLabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SystemNetworkNames != nil {
		in, out := &in.SystemNetworkNames, &out.SystemNetworkNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.RolloutStrategy.DeepCopyInto(&out.RolloutStrategy)
	in.EligibleNodesDriftPolicy.DeepCopyInto(&out.EligibleNodesDriftPolicy)
	out.EligibleNodesPolicy = in.EligibleNodesPolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassSpec.
func (in *ReplicatedStorageClassSpec) DeepCopy() *ReplicatedStorageClassSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassStatus) DeepCopyInto(out *ReplicatedStorageClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ReplicatedStorageClassConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.EligibleNodesWorldState != nil {
		in, out := &in.EligibleNodesWorldState, &out.EligibleNodesWorldState
		*out = new(ReplicatedStorageClassEligibleNodesWorldState)
		(*in).DeepCopyInto(*out)
	}
	if in.EligibleNodes != nil {
		in, out := &in.EligibleNodes, &out.EligibleNodes
		*out = make([]ReplicatedStorageClassEligibleNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Volumes.DeepCopyInto(&out.Volumes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassStatus.
func (in *ReplicatedStorageClassStatus) DeepCopy() *ReplicatedStorageClassStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStorageClassVolumesSummary) DeepCopyInto(out *ReplicatedStorageClassVolumesSummary) {
	*out = *in
	if in.Total != nil {
		in, out := &in.Total, &out.Total
		*out = new(int32)
		**out = **in
	}
	if in.PendingAcknowledgment != nil {
		in, out := &in.PendingAcknowledgment, &out.PendingAcknowledgment
		*out = new(int32)
		**out = **in
	}
	if in.Aligned != nil {
		in, out := &in.Aligned, &out.Aligned
		*out = new(int32)
		**out = **in
	}
	if in.EligibleNodesViolation != nil {
		in, out := &in.EligibleNodesViolation, &out.EligibleNodesViolation
		*out = new(int32)
		**out = **in
	}
	if in.StaleConfiguration != nil {
		in, out := &in.StaleConfiguration, &out.StaleConfiguration
		*out = new(int32)
		**out = **in
	}
	if in.RollingUpdatesInProgress != nil {
		in, out := &in.RollingUpdatesInProgress, &out.RollingUpdatesInProgress
		*out = make([]ReplicatedStorageClassRollingUpdateInProgress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStorageClassVolumesSummary.
func (in *ReplicatedStorageClassVolumesSummary) DeepCopy() *ReplicatedStorageClassVolumesSummary {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStorageClassVolumesSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStoragePool) DeepCopyInto(out *ReplicatedStoragePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStoragePool.
func (in *ReplicatedStoragePool) DeepCopy() *ReplicatedStoragePool {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStoragePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedStoragePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStoragePoolLVMVolumeGroups) DeepCopyInto(out *ReplicatedStoragePoolLVMVolumeGroups) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStoragePoolLVMVolumeGroups.
func (in *ReplicatedStoragePoolLVMVolumeGroups) DeepCopy() *ReplicatedStoragePoolLVMVolumeGroups {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStoragePoolLVMVolumeGroups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStoragePoolList) DeepCopyInto(out *ReplicatedStoragePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReplicatedStoragePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStoragePoolList.
func (in *ReplicatedStoragePoolList) DeepCopy() *ReplicatedStoragePoolList {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStoragePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedStoragePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStoragePoolSpec) DeepCopyInto(out *ReplicatedStoragePoolSpec) {
	*out = *in
	if in.LVMVolumeGroups != nil {
		in, out := &in.LVMVolumeGroups, &out.LVMVolumeGroups
		*out = make([]ReplicatedStoragePoolLVMVolumeGroups, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStoragePoolSpec.
func (in *ReplicatedStoragePoolSpec) DeepCopy() *ReplicatedStoragePoolSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStoragePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedStoragePoolStatus) DeepCopyInto(out *ReplicatedStoragePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedStoragePoolStatus.
func (in *ReplicatedStoragePoolStatus) DeepCopy() *ReplicatedStoragePoolStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicatedStoragePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolume) DeepCopyInto(out *ReplicatedVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolume.
func (in *ReplicatedVolume) DeepCopy() *ReplicatedVolume {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeAttachment) DeepCopyInto(out *ReplicatedVolumeAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeAttachment.
func (in *ReplicatedVolumeAttachment) DeepCopy() *ReplicatedVolumeAttachment {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedVolumeAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeAttachmentList) DeepCopyInto(out *ReplicatedVolumeAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReplicatedVolumeAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeAttachmentList.
func (in *ReplicatedVolumeAttachmentList) DeepCopy() *ReplicatedVolumeAttachmentList {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedVolumeAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeAttachmentSpec) DeepCopyInto(out *ReplicatedVolumeAttachmentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeAttachmentSpec.
func (in *ReplicatedVolumeAttachmentSpec) DeepCopy() *ReplicatedVolumeAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeAttachmentStatus) DeepCopyInto(out *ReplicatedVolumeAttachmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeAttachmentStatus.
func (in *ReplicatedVolumeAttachmentStatus) DeepCopy() *ReplicatedVolumeAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeEligibleNodesViolation) DeepCopyInto(out *ReplicatedVolumeEligibleNodesViolation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeEligibleNodesViolation.
func (in *ReplicatedVolumeEligibleNodesViolation) DeepCopy() *ReplicatedVolumeEligibleNodesViolation {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeEligibleNodesViolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeList) DeepCopyInto(out *ReplicatedVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReplicatedVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeList.
func (in *ReplicatedVolumeList) DeepCopy() *ReplicatedVolumeList {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeReplica) DeepCopyInto(out *ReplicatedVolumeReplica) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeReplica.
func (in *ReplicatedVolumeReplica) DeepCopy() *ReplicatedVolumeReplica {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeReplica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedVolumeReplica) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeReplicaList) DeepCopyInto(out *ReplicatedVolumeReplicaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReplicatedVolumeReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeReplicaList.
func (in *ReplicatedVolumeReplicaList) DeepCopy() *ReplicatedVolumeReplicaList {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeReplicaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedVolumeReplicaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeReplicaSpec) DeepCopyInto(out *ReplicatedVolumeReplicaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeReplicaSpec.
func (in *ReplicatedVolumeReplicaSpec) DeepCopy() *ReplicatedVolumeReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeReplicaStatus) DeepCopyInto(out *ReplicatedVolumeReplicaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DRBD != nil {
		in, out := &in.DRBD, &out.DRBD
		*out = new(DRBD)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeReplicaStatus.
func (in *ReplicatedVolumeReplicaStatus) DeepCopy() *ReplicatedVolumeReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeRolloutTicket) DeepCopyInto(out *ReplicatedVolumeRolloutTicket) {
	*out = *in
	in.Configuration.DeepCopyInto(&out.Configuration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeRolloutTicket.
func (in *ReplicatedVolumeRolloutTicket) DeepCopy() *ReplicatedVolumeRolloutTicket {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeRolloutTicket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeSpec) DeepCopyInto(out *ReplicatedVolumeSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeSpec.
func (in *ReplicatedVolumeSpec) DeepCopy() *ReplicatedVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeStatus) DeepCopyInto(out *ReplicatedVolumeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DRBD != nil {
		in, out := &in.DRBD, &out.DRBD
		*out = new(DRBDResource)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceMinor != nil {
		in, out := &in.DeviceMinor, &out.DeviceMinor
		*out = new(DeviceMinor)
		**out = **in
	}
	if in.ActuallyAttachedTo != nil {
		in, out := &in.ActuallyAttachedTo, &out.ActuallyAttachedTo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DesiredAttachTo != nil {
		in, out := &in.DesiredAttachTo, &out.DesiredAttachTo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActualSize != nil {
		in, out := &in.ActualSize, &out.ActualSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(ReplicatedVolumeStorageClassReference)
		**out = **in
	}
	if in.RolloutTicket != nil {
		in, out := &in.RolloutTicket, &out.RolloutTicket
		*out = new(ReplicatedVolumeRolloutTicket)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetConfiguration != nil {
		in, out := &in.TargetConfiguration, &out.TargetConfiguration
		*out = new(ReplicatedVolumeStorageClassConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.EligibleNodesViolations != nil {
		in, out := &in.EligibleNodesViolations, &out.EligibleNodesViolations
		*out = make([]ReplicatedVolumeEligibleNodesViolation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeStatus.
func (in *ReplicatedVolumeStatus) DeepCopy() *ReplicatedVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeStorageClassConfiguration) DeepCopyInto(out *ReplicatedVolumeStorageClassConfiguration) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SystemNetworkNames != nil {
		in, out := &in.SystemNetworkNames, &out.SystemNetworkNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeStorageClassConfiguration.
func (in *ReplicatedVolumeStorageClassConfiguration) DeepCopy() *ReplicatedVolumeStorageClassConfiguration {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeStorageClassConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedVolumeStorageClassReference) DeepCopyInto(out *ReplicatedVolumeStorageClassReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedVolumeStorageClassReference.
func (in *ReplicatedVolumeStorageClassReference) DeepCopy() *ReplicatedVolumeStorageClassReference {
	if in == nil {
		return nil
	}
	out := new(ReplicatedVolumeStorageClassReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedSecretUnsupportedAlgError) DeepCopyInto(out *SharedSecretUnsupportedAlgError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedSecretUnsupportedAlgError.
func (in *SharedSecretUnsupportedAlgError) DeepCopy() *SharedSecretUnsupportedAlgError {
	if in == nil {
		return nil
	}
	out := new(SharedSecretUnsupportedAlgError)
	in.DeepCopyInto(out)
	return out
}
