{{- include "helm_lib_csi_controller_rbac" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linstor-csi-node
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-node")) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:{{ .Chart.Name }}:replicated-resources-reader
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
rules:
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["replicatedstoragepools", "replicatedstorageclasses", "lvmvolumegroups"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:replicated-resources-reader-binding
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: csi
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:replicated-resources-reader
  apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: d8:{{ .Chart.Name }}:rsc-watcher
#   {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
# rules:
#   - apiGroups: ["storage.deckhouse.io"]
#     resources: ["replicatedstorageclasses"]
#     verbs: ["get", "list", "watch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: d8:{{ .Chart.Name }}:rsc-read-access
#   {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
# subjects:
#   - kind: ServiceAccount
#     name: csi
#     namespace: d8-{{ .Chart.Name }}
# roleRef:
#   kind: ClusterRole
#   name: d8:{{ .Chart.Name }}:rsc-watcher
#   apiGroup: rbac.authorization.k8s.io
