{{- include "helm_lib_csi_controller_rbac" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linstor-csi-node
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-node")) | nindent 2 }}
