{{- include "helm_lib_csi_controller_rbac" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linstor-csi-node
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-node")) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:{{ .Chart.Name }}:storagepool-reader
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
rules:
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["replicatedstoragepools", "lvmvolumegroups"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:storagepool-reader-binding
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: csi
    namespace: d8-sds-replicated-volume
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:storagepool-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:{{ .Chart.Name }}:rsc-watcher
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
rules:
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["replicatedstorageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:rsc-read-access
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: csi
    namespace: d8-sds-replicated-volume
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:rsc-watcher
  apiGroup: rbac.authorization.k8s.io



---
{{- include "helm_lib_csi_controller_rbac" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:{{ .Chart.Name }}:drbdclusters-manager
    {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
rules:
  - apiGroups: ["storage.deckhouse.io"]
    resources: ["drbdclusters"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:drbdclusters-access
    {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: csi
    namespace: d8-sds-replicated-volume
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:drbdclusters-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:{{ .Chart.Name }}:drbd-sync-resource-accessor
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
rules:
  - apiGroups: ["internal.linstor.linbit.com"]
    resources: ["resourcegroups", "resourcedefinitions", "volumedefinitions", "layerdrbdresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:drbd-sync-resource-read-access
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: csi
    namespace: d8-sds-replicated-volume
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:drbd-sync-resource-accessor
  apiGroup: rbac.authorization.k8s.io 
