{{- if (.Values.global.enabledModules | has "snapshot-controller") }}
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-csi-controller")) | nindent 2 }}
  name: {{ .Chart.Name }}
driver: replicated.csi.deckhouse.io
deletionPolicy: Delete
{{- end }}
