- name: kubernetes.drbd.device_state
  rules:
    - alert: D8LinstorVolumeIsNotHealthy
      expr: max by (node, resource) ((linstor_volume_state != 1) != 4)
      for: 5m
      labels:
        severity_level: "6"
        tier: cluster
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: LINSTOR volume is not healthy
        description: |
          LINSTOR volume {{ $labels.resource }} on node {{ $labels.node }} is not healthy

          Please, contact tech support for assistance.

    - alert: D8DrbdDeviceHasNoQuorum
      expr: max by (node, name) (drbd_device_quorum == 0)
      for: 5m
      labels:
        severity_level: "6"
        tier: cluster
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: DRBD device has no quorum
        description: |
          DRBD device {{ $labels.name }} on node {{ $labels.node }} has no quorum.

          Please, contact tech support for assistance.

    - alert: D8DrbdDeviceIsUnintentionalDiskless
      expr: max by (node, name) (drbd_device_unintentionaldiskless == 1)
      for: 5m
      labels:
        severity_level: "6"
        tier: cluster
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: DRBD device is unintentional diskless
        description: |
          DRBD device {{ $labels.name }} on node {{ $labels.node }} unintentionally switched to diskless mode

          Please, contact tech support for assistance.

    - alert: D8DrbdPeerDeviceIsOutOfSync
      expr: max by (node, conn_name, name) (drbd_peerdevice_outofsync_bytes > 0)
      for: 5m
      labels:
        severity_level: "6"
        tier: cluster
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: DRBD device has out-of-sync data
        description: |
          DRBD device {{ $labels.name }} on node {{ $labels.node }} has out-of-sync data with {{ $labels.conn_name }}

          The recommended course of action:
          1. Login into node with the problem:

             ```
             kubectl -n d8-sds-replicated-volume exec -ti $(kubectl -n d8-sds-replicated-volume get pod --field-selector=spec.nodeName={{ $labels.node }} -l app=linstor-node -o name) -c linstor-satellite -- bash
             ```

          2. Check the LINSTOR peer node state:

             ```
             linstor node list -n {{ $labels.conn_name }}
             ```

          3. Check the LINSTOR resource states:

             ```
             linstor resource list -r {{ $labels.name }}
             ```

          4. View the status of the DRBD device on the node and try to figure out why it has out-of-sync data with {{ $labels.conn_name }}:

             ```
             drbdsetup status {{ $labels.name }} --statistics
             dmesg --color=always | grep 'drbd {{ $labels.name }}'
             ```

          5. Consider reconnect resource with the peer node:

             ```
             drbdadm disconnect {{ $labels.name }}:{{ $labels.conn_name }}
             drbdadm connect {{ $labels.name }}:{{ $labels.conn_name }}
             ```

          6. Check if problem has solved, device should have no out-of-sync data:

             ```
             drbdsetup status {{ $labels.name }} --statistics
             ```

    - alert: D8DrbdDeviceIsNotConnected
      expr: max by (node, conn_name, name) (drbd_connection_state{drbd_connection_state!="UpToDate", drbd_connection_state!="Connected"} == 1)
      for: 5m
      labels:
        severity_level: "6"
        tier: cluster
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_drbd_device_health: "D8DrbdDeviceHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: DRBD device is not connected
        description: |
          DRBD device {{ $labels.name }} on node {{ $labels.node }} is not connected with {{ $labels.conn_name }}


          Please, contact tech support for assistance.
