- name: kubernetes.certs.expiring_soon_check
  rules:
    - alert: CertificateExpiringIn30d
      expr: count(kube_secret_labels{label_storage_deckhouse_io_sds-replicated-volume-cert-expire-in-30d="true"}) > 0
      for: 5m
      labels:
        severity: warning
        tier: cluster
      annotations:
        summary: Certificates expiring within 30 days detected
        description: |
          One or more Kubernetes Secrets contain certificates that are due to expire in under 30 days.
          Please check the certificate details and renew or rotate them to avoid downtime.
          
          Use the following to list them:
          `kubectl get secrets -n d8-sds-replicated-volume -l storage.deckhouse.io/sds-replicated-volume-cert-expire-in-30d=true`
          
          Recommended next steps:
          1. Review your certificate issuance or rotation process.
          2. Renew certificates and update the affected secrets.
