- name: kubernetes.sds_drbd.storage_class
  rules:
    - alert: SDSDRBDModuleNeedsMigration
      expr: d8_kubernetes_version == 1
      for: 5m
      labels:
        severity_level: "4"
        tier: cluster
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__d8_module_needs_migration: "D8ModuleNeedsMigration,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_module_needs_migration: "D8ModuleNeedsMigration,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: Module sds-drbd needs migration to sds-replicated-volume.
        description: |
          Module sds-drbd needs migration to sds-replicated-volume.

          Migration docs can be found here: 
          `https://deckhouse.io/modules/sds-replicated-volume/stable/faq.html#migrating-from-sds-drbd-module-to-sds-replicated-volume`
