{{- if .Values.sdsReplicatedVolume.useLinstor }}
{{- /*
  TODO: This secret should be removed after almost all clients moved to 1.64+ Deckhouse version (February 2025?).
  Also remove it from hooks/generate_webhook_certs.py and set in module.yaml following:
  requirements:
    deckhouse: >= 1.64
*/}}
---
apiVersion: v1
kind: Secret
metadata:
  name: linstor-scheduler-admission-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-scheduler-admission")) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- with .Values.sdsReplicatedVolume.internal.webhookCert }}
  tls.crt: {{ .crt | b64enc }}
  tls.key: {{ .key | b64enc }}
  ca.crt: {{ .ca | b64enc }}
  {{- end }}
{{- end }}