{{- if and (not (eq "dev" .Values.global.deckhouseVersion)) (semverCompare "<1.64" .Values.global.deckhouseVersion) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: linstor-scheduler-admission-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-scheduler-admission")) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- with .Values.sdsReplicatedVolume.internal.webhookCert }}
  tls.crt: {{ .crt }}
  tls.key: {{ .key }}
  ca.crt: {{ .ca }}
  {{- end }}
{{- end }}