---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-network-discoverer
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "storage-network-discoverer")) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:{{ .Chart.Name }}:storage-network-discoverer
  {{- include "helm_lib_module_labels" (list . (dict "app" "storage-network-discoverer")) | nindent 2 }}
rules:
  - apiGroups:
      - deckhouse.io
    resources:
      - moduleconfigs
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - get
      - list
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:storage-network-discoverer
  {{- include "helm_lib_module_labels" (list . (dict "app" "storage-network-discoverer")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: storage-network-discoverer
    namespace: d8-{{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:storage-network-discoverer
