apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: drbdnodes.storage.deckhouse.io
spec:
  group: storage.deckhouse.io
  scope: Namespaced
  names:
    plural: drbdnodes
    singular: drbdnode
    kind: DRBDNode
    shortNames:
      - drbdn
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                networkPools:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      address:
                        type: object
                        properties:
                          ipv4:
                            type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
