---
apiVersion: v1
kind: Secret
metadata:
  name: linstor-controller-https-cert
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict
    "storage.deckhouse.io/internal-cert-name" "httpsControllerCert"
  )) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- with .Values.sdsReplicatedVolume.internal.httpsControllerCert }}
  tls.crt: {{ .crt }}
  tls.key: {{ .key }}
  ca.crt: {{ .ca }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: linstor-client-https-cert
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict
    "storage.deckhouse.io/internal-cert-name" "httpsClientCert"
  )) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- with .Values.sdsReplicatedVolume.internal.httpsClientCert }}
  tls.crt: {{ .crt }}
  tls.key: {{ .key }}
  ca.crt: {{ .ca }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: linstor-controller-ssl-cert
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict
    "storage.deckhouse.io/internal-cert-name" "sslControllerCert"
  )) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- with .Values.sdsReplicatedVolume.internal.sslControllerCert }}
  tls.crt: {{ .crt }}
  tls.key: {{ .key }}
  ca.crt: {{ .ca }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: linstor-node-ssl-cert
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict
    "storage.deckhouse.io/internal-cert-name" "sslNodeCert"
  )) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- with .Values.sdsReplicatedVolume.internal.sslNodeCert }}
  tls.crt: {{ .crt }}
  tls.key: {{ .key }}
  ca.crt: {{ .ca }}
  {{- end }}
