---
apiVersion: v1
kind: Secret
metadata:
  name: spaas-certs-2
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "spaas")) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- with .Values.sdsReplicatedVolume.internal.spaasCert2 }}
  tls.crt: {{ .crt }}
  tls.key: {{ .key }}
  ca.crt: {{ .ca }}
  {{- end }}
