{{- if not .Values.sdsReplicatedVolume.useLinstor }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linstor-node-monitoring
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "linstor-node")) | nindent 2 }}
data:
  prometheus.toml: |2

    [[prometheus]]
    address = "127.0.0.1:4215"
    enums = true
{{- end }}