---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sds-replicated-volume-controller-config
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
data:
{{- if has "virtualization" .Values.global.enabledModules }}
  virtualizationEnabled: "true"
{{- else }}
  virtualizationEnabled: "false"
{{- end }}
