---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sds-replicated-volume-controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sds-replicated-volume-controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - list
      - delete
      - update
      - create

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:sds-replicated-volume-controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - replicatedstorageclasses
      - lvmvolumegroups
      - replicatedstoragepools
    verbs:
      - get
      - list
      - create
      - delete
      - watch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
      - csinodes
    verbs:
      - create
      - delete
      - list
      - get
      - watch
      - update
  - apiGroups:
      - internal.linstor.linbit.com
    resources:
      - propscontainers
    verbs:
      - list
      - get
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sds-replicated-volume-controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: sds-replicated-volume-controller
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: Role
  name: sds-replicated-volume-controller
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:sds-replicated-volume-controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: sds-replicated-volume-controller
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:sds-replicated-volume-controller
  apiGroup: rbac.authorization.k8s.io


