---
apiVersion: v1
kind: Secret
metadata:
  name: d8-sds-replicated-volume-controller-config
  namespace: d8-{{ .Chart.Name }}
type: Opaque
stringData:
  config: |-
    nodeSelector: {{ .Values.sdsReplicatedVolume.dataNodes.nodeSelector | toYaml | nindent 6 }}
