{{- if .Values.sdsReplicatedVolume.useLinstor }}
---
apiVersion: v1
kind: Secret
metadata:
  name: d8-sds-replicated-volume-controller-config
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-controller")) | nindent 2 }}
type: Opaque
stringData:
  config: |-
    nodeSelector: {{ .Values.sdsReplicatedVolume.dataNodes.nodeSelector | toYaml | nindent 6 }}
{{- end }}
