name: Build and push for prod

env:
  MODULES_REGISTRY: ${{ vars.PROD_REGISTRY }}
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}
  MODULES_MODULE_NAME: ${{ vars.MODULE_NAME }}
  MODULE_SOURCE_NAME: ${{ vars.PROD_MODULE_SOURCE_NAME }}
  MODULES_REGISTRY_LOGIN: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
  MODULES_REGISTRY_PASSWORD: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
  MODULES_MODULE_TAG: ${{ github.ref_name }}
  GOLANG_VERSION: ${{ vars.GOLANG_VERSION }}
  GOPROXY: ${{ secrets.GOPROXY }}
  SOURCE_REPO: ${{ secrets.SOURCE_REPO }}
  SOURCE_REPO_SSH_KEY: ${{ secrets.SOURCE_REPO_SSH_KEY }}
  BASE_IMAGES_VERSION: "v0.4.3"

on:
  push:
    tags:
      - "**"

jobs:
  prod_ce_setup_build:
    runs-on: [self-hosted, large]
    name: Build and Push CE
    steps:
      - name: SET VAR
        run: |
          echo "MODULES_MODULE_SOURCE=$MODULES_REGISTRY/$MODULE_SOURCE_NAME/ce/modules" >> "$GITHUB_ENV"
          echo "MODULE_EDITION=ce" >> "$GITHUB_ENV"
      - run: |
          echo $MODULES_REGISTRY
          echo $MODULES_MODULE_NAME
          echo $MODULES_MODULE_SOURCE
          echo $MODULES_MODULE_TAG
          echo $MODULE_EDITION
        shell: bash
        name: Show vars

      - uses: actions/checkout@v4

      - name: Download base images and auth prepare
        run: |
          wget https://fox.flant.com/api/v4/projects/deckhouse%2Fbase-images/packages/generic/base_images/$BASE_IMAGES_VERSION/base_images.yml -O base_images.yml
          cat base_images.yml

      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          registry_login: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/build@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/ce/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.ref_name }}
          secondary_repo: "${{ vars.DEV_MODULE_SOURCE }}/${{ vars.MODULE_NAME }}"
          source_repo: ${{ secrets.SOURCE_REPO }}
          source_repo_ssh_key: ${{ secrets.SOURCE_REPO_SSH_KEY }}

  prod_ee_setup_build:
    runs-on: [self-hosted, large]
    name: Build and Push EE
    steps:
      - name: SET VAR
        run: |
          echo "MODULES_MODULE_SOURCE=$MODULES_REGISTRY/$MODULE_SOURCE_NAME/ee/modules" >> "$GITHUB_ENV"
          echo "MODULE_EDITION=ee" >> "$GITHUB_ENV"
      - run: |
          echo $MODULES_REGISTRY
          echo $MODULES_MODULE_NAME
          echo $MODULES_MODULE_SOURCE
          echo $MODULES_MODULE_TAG
          echo $MODULE_EDITION
        shell: bash
        name: Show vars

      - uses: actions/checkout@v4

      - name: Download base images
        run: |
          wget https://fox.flant.com/api/v4/projects/deckhouse%2Fbase-images/packages/generic/base_images/$BASE_IMAGES_VERSION/base_images.yml -O base_images.yml
          cat base_images.yml

      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          registry_login: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/build@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/ee/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.ref_name }}
          secondary_repo: "${{ vars.DEV_MODULE_SOURCE }}/${{ vars.MODULE_NAME }}"
          source_repo: ${{ secrets.SOURCE_REPO }}
          source_repo_ssh_key: ${{ secrets.SOURCE_REPO_SSH_KEY }}

  prod_fe_setup_build:
    runs-on: [self-hosted, large]
    name: Build and Push FE
    steps:
      - name: SET VAR
        run: |
          echo "MODULES_MODULE_SOURCE=$MODULES_REGISTRY/$MODULE_SOURCE_NAME/fe/modules" >> "$GITHUB_ENV"
          echo "MODULE_EDITION=ee" >> "$GITHUB_ENV"
      - run: |
          echo $MODULES_REGISTRY
          echo $MODULES_MODULE_NAME
          echo $MODULES_MODULE_SOURCE
          echo $MODULES_MODULE_TAG
          echo $MODULE_EDITION
        shell: bash
        name: Show vars

      - uses: actions/checkout@v4

      - name: Download base images
        run: |
          wget https://fox.flant.com/api/v4/projects/deckhouse%2Fbase-images/packages/generic/base_images/$BASE_IMAGES_VERSION/base_images.yml -O base_images.yml
          cat base_images.yml

      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          registry_login: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/build@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/fe/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.ref_name }}
          secondary_repo: "${{ vars.DEV_MODULE_SOURCE }}/${{ vars.MODULE_NAME }}"
          source_repo: ${{ secrets.SOURCE_REPO }}
          source_repo_ssh_key: ${{ secrets.SOURCE_REPO_SSH_KEY }}

  prod_se_setup_build:
    runs-on: [self-hosted, large]
    name: Build and Push SE
    steps:
      - name: SET VAR
        run: |
          echo "MODULES_MODULE_SOURCE=$MODULES_REGISTRY/$MODULE_SOURCE_NAME/se/modules" >> "$GITHUB_ENV"
          echo "MODULE_EDITION=se" >> "$GITHUB_ENV"
      - run: |
          echo $MODULES_REGISTRY
          echo $MODULES_MODULE_NAME
          echo $MODULES_MODULE_SOURCE
          echo $MODULES_MODULE_TAG
          echo $MODULE_EDITION
        shell: bash
        name: Show vars

      - uses: actions/checkout@v4

      - name: Download base images
        run: |
          wget https://fox.flant.com/api/v4/projects/deckhouse%2Fbase-images/packages/generic/base_images/$BASE_IMAGES_VERSION/base_images.yml -O base_images.yml
          cat base_images.yml

      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          registry_login: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/build@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/se/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.ref_name }}
          secondary_repo: "${{ vars.DEV_MODULE_SOURCE }}/${{ vars.MODULE_NAME }}"
          source_repo: ${{ secrets.SOURCE_REPO }}
          source_repo_ssh_key: ${{ secrets.SOURCE_REPO_SSH_KEY }}

  prod_se_plus_setup_build:
    runs-on: [self-hosted, large]
    name: Build and Push SE+
    steps:
      - name: SET VAR
        run: |
          echo "MODULES_MODULE_SOURCE=$MODULES_REGISTRY/$MODULE_SOURCE_NAME/se-plus/modules" >> "$GITHUB_ENV"
          echo "MODULE_EDITION=seplus" >> "$GITHUB_ENV"
      - run: |
          echo $MODULES_REGISTRY
          echo $MODULES_MODULE_NAME
          echo $MODULES_MODULE_SOURCE
          echo $MODULES_MODULE_TAG
          echo $MODULE_EDITION
        shell: bash
        name: Show vars

      - uses: actions/checkout@v4

      - name: Download base images
        run: |
          wget https://fox.flant.com/api/v4/projects/deckhouse%2Fbase-images/packages/generic/base_images/$BASE_IMAGES_VERSION/base_images.yml -O base_images.yml
          cat base_images.yml

      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          registry_login: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/build@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/se-plus/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.ref_name }}
          secondary_repo: "${{ vars.DEV_MODULE_SOURCE }}/${{ vars.MODULE_NAME }}"
          source_repo: ${{ secrets.SOURCE_REPO }}
          source_repo_ssh_key: ${{ secrets.SOURCE_REPO_SSH_KEY }}