name: PR Checks

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  release-label:
    name: Release note label
    runs-on: [self-hosted, regular]

    steps:
      - name: Check minimum labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "release-note/dependencies, dependencies, release-note/deprecation, release-note/breaking-change, release-note/bug, bug, release-note/enhancement, enhancement, release-note/documentation, documentation, release-note/new-feature, release-note/ignore"
