name: Build and checks

on:
  schedule:
    - cron: "0 01 * * 0,3" # Regular CVE scan
  pull_request:
    types: [opened, reopened, labeled, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Optional. Set minor version of release you want to scan. e.g.: 1.23"
        required: false
      scan_several_lastest_releases:
        description: "Optional. Whether to scan last several releases or not. true/false. For scheduled pipelines it is always true. Default is: false."
        required: false
      latest_releases_amount:
        description: "Optional. Number of latest releases to scan. Default is: 3"
        required: false
      severity:
        description: "Optional. Vulnerabilities severity to scan. Default is: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
        required: false
      svace_enabled:
        description: "Enable svace build and analyze"
        type: boolean
        required: false

jobs:
  build_dev:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/build_dev.yml
    secrets: inherit
    with:
      svace_enabled: ${{ github.event.inputs.svace_enabled && true || false }}
  cve_scan_on_pr:
    if: github.event_name == 'pull_request'
    name: CVE scan for PR
    runs-on: [self-hosted, regular]
    needs: [build_dev]
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/cve_scan@v6
        with:
          tag: pr${{ github.event.number }}
          tag_type: "dev"
          module_name: ${{ vars.MODULE_NAME }}
          dd_url: ${{ secrets.DEFECTDOJO_HOST }}
          dd_token: ${{ secrets.DEFECTDOJO_API_TOKEN }}
          prod_registry: "registry.deckhouse.io"
          prod_registry_user: "license-token"
          prod_registry_password: ${{ secrets.PROD_MODULES_READ_REGISTRY_PASSWORD }}
          dev_registry: ${{ vars.DEV_REGISTRY }}
          dev_registry_user: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          dev_registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
          deckhouse_private_repo: ${{ secrets.DECKHOUSE_PRIVATE_REPO }}
          severity: "HIGH,CRITICAL"
  cve_scan:
    if: github.event_name != 'pull_request'
    name: Regular CVE scan
    runs-on: [self-hosted, regular]
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/cve_scan@v6
        with:
          tag: ${{ github.event.inputs.release_branch || github.event.repository.default_branch }}
          tag_type: "dev"
          module_name: ${{ vars.MODULE_NAME }}
          dd_url: ${{ secrets.DEFECTDOJO_HOST }}
          dd_token: ${{ secrets.DEFECTDOJO_API_TOKEN }}
          prod_registry: "registry.deckhouse.io"
          prod_registry_user: "license-token"
          prod_registry_password: ${{ secrets.PROD_MODULES_READ_REGISTRY_PASSWORD }}
          dev_registry: ${{ vars.DEV_REGISTRY }}
          dev_registry_user: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          dev_registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
          deckhouse_private_repo: ${{ secrets.DECKHOUSE_PRIVATE_REPO }}
          scan_several_lastest_releases: ${{ github.event.inputs.scan_several_lastest_releases }}
          latest_releases_amount: ${{ github.event.inputs.latest_releases_amount || '3' }}
          severity: ${{ github.event.inputs.severity }}
