name: Trivy check for sub repos

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Trivy check for sub repos
    runs-on: [self-hosted, regular]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
