{{- if not .Values.sdsReplicatedVolume.newControlPlane }}
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: replicated.csi.storage.deckhouse.io
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: false
  seLinuxMount: true
  storageCapacity: true
  volumeLifecycleModes:
    - Persistent
{{- end }}


{{- if .Values.sdsReplicatedVolume.newControlPlane }}
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: replicated.csi.storage.deckhouse.io
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: true
  seLinuxMount: true
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
{{- end }}
