{{- include "helm_lib_csi_controller_rbac" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:sds-replicated-volume-csi-controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-csi-controller")) | nindent 2 }}
rules:
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - lvmvolumegroups
      - lvmlogicalvolumes
      - lvmlogicalvolumesnapshots
      - localstorageclasses
      - replicatedstoragepools
      - replicatedstorageclasses
      - replicatedvolumes
    verbs:
      - get
      - list
      - create
      - delete
      - watch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:sds-replicated-volume-csi-controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-replicated-volume-csi-controller")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: csi
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:sds-replicated-volume-csi-controller
  apiGroup: rbac.authorization.k8s.io

